/* ============================================================================
   03 - sp_WhoIsActive logging.

   PREREQUISITE: Adam Machanic's sp_WhoIsActive must already be installed in
   master. It is not redistributed here. Get it from
   https://github.com/amachanic/sp_whoisactive and install it before running
   this script.

   What this sampler is for, and what it is not for:

   A sampler catches a query only if the query is running when the sample
   fires, with probability roughly duration/interval. On an OLTP workload with
   a p99 in the low milliseconds, a one-minute sampler will essentially never
   catch a normal query, and it cannot be used to count executions or measure
   typical latency — that is what query_stat_delta and xe_workload are for.

   What it does catch is what LASTS: maintenance windows, integration jobs,
   blocking chains, and anything pathological. Those rows are the point.
   ============================================================================ */
USE [$(TelemetryDatabase)];
GO
IF NOT EXISTS (SELECT 1 FROM master.sys.objects WHERE name = 'sp_WhoIsActive')
BEGIN
    RAISERROR('sp_WhoIsActive is not installed in master. Install it first, then re-run this script.', 16, 1);
END
GO

/* The destination table's shape depends on which @get_* options are used, so
   it is generated by sp_WhoIsActive itself. The collector below MUST pass the
   same flags, or the insert fails on a column mismatch. */
IF OBJECT_ID('dbo.who_is_active') IS NULL
BEGIN
    DECLARE @schema nvarchar(max);
    EXEC master.dbo.sp_WhoIsActive
         @get_transaction_info = 1,
         @get_outer_command    = 1,
         @get_task_info        = 2,
         @find_block_leaders   = 1,
         @return_schema        = 1,
         @schema               = @schema OUTPUT;
    SET @schema = REPLACE(@schema, '<table_name>', '$(TelemetryDatabase).dbo.who_is_active');
    EXEC (@schema);
END
GO
IF OBJECT_ID('dbo.who_is_active') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes
                    WHERE name = 'ix_wia_collection_time'
                      AND object_id = OBJECT_ID('dbo.who_is_active'))
    CREATE NONCLUSTERED INDEX ix_wia_collection_time ON dbo.who_is_active (collection_time);
GO

IF OBJECT_ID('dbo.usp_collect_who_is_active') IS NOT NULL
    DROP PROCEDURE dbo.usp_collect_who_is_active;
GO
/* ---------------------------------------------------------------------------
   Noise filter. Raw output on a busy instance is dominated by sessions that
   are alive but not working. Measured shape of a typical sample:

     background          engine-internal workers, never application work
     dormant             idle pooled connections
     DatabaseMail        Service Broker queue readers, PERMANENTLY parked in
                         WAITFOR. These show many minutes of elapsed time in
                         every single sample and will dominate any
                         "long-running session" report with behaviour that is
                         completely normal.
     sleeping + open tran  KEPT: a long-open transaction retains log and
                         causes blocking. Genuine risk signal.
     suspended / running   KEPT: actually waiting on something.

   The filter is by PROGRAM, not by database. Excluding msdb wholesale here
   would hide a genuinely stuck Agent job.
   --------------------------------------------------------------------------- */
CREATE PROCEDURE dbo.usp_collect_who_is_active
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @run_id bigint, @node sysname = CONVERT(sysname, SERVERPROPERTY('MachineName')),
            @rows bigint = 0, @t datetime;

    INSERT INTO dbo.collection_run (collector, node_name) VALUES ('who_is_active', @node);
    SET @run_id = SCOPE_IDENTITY();

    BEGIN TRY
        EXEC master.dbo.sp_WhoIsActive
             @get_transaction_info = 1,
             @get_outer_command    = 1,
             @get_task_info        = 2,
             @find_block_leaders   = 1,
             @destination_table    = '$(TelemetryDatabase).dbo.who_is_active';

        /* @@ROWCOUNT after sp_WhoIsActive reflects one of its internal
           statements, not the rows inserted, so the count is taken from the
           table instead. */
        SELECT @t = MAX(collection_time) FROM dbo.who_is_active;

        DELETE FROM dbo.who_is_active
         WHERE collection_time = @t
           AND (status IN ('background', 'dormant')
                OR [program_name] LIKE 'DatabaseMail%');

        SELECT @rows = COUNT(*) FROM dbo.who_is_active WHERE collection_time = @t;

        UPDATE dbo.collection_run SET ended_at = SYSUTCDATETIME(), rows_written = @rows, status = 'ok'
         WHERE run_id = @run_id;
    END TRY
    BEGIN CATCH
        UPDATE dbo.collection_run SET ended_at = SYSUTCDATETIME(), status = 'error',
               error_message = LEFT(ERROR_MESSAGE(), 2000) WHERE run_id = @run_id;
        THROW;
    END CATCH
END
GO
PRINT '03 - who_is_active logging ready.';
GO
